site_name: Wokelib
theme: readthedocs

nav:
  - Home: index.md
  - API Reference: api_reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true


