
test = 5
[flows]
min_int=55

[flows.flow1]
weight=50 
amount.max=59
amount.edge_values_prob=0.05

[flows.flow2]
weight=50 
amount.edge_values_prob=0.05

addresses.len=3

[flows.flow3]
weight=50 
amounts.edge_values_prob=0.05
amounts.len=3

[flows.flow4]
weight=50 
prob.edge_values_prob=0.05

[flows.flow5]
weight=50 
doit.true_prob=0.95
